### ISSUE TITLE
Segmentation fault on server shutdown with players on

### ISSUE THREAD

**Issue by ghost** [nosoop/SM-TFAttributeSupport#14]
For some reason when I shutdown the server with players on a segfault always happens. If I start the server and then shutdown it does not happen. When I disable the plugin it does not happen. Only Accelerator, base SM plugins and dependencies were installed. Accelerator did not upload the crash dump since the server was shutting down. Latest Metamod (1.12) and SourceMod (1.11), latest plugin release.

**Comment by nosoop** [comment]
I'm fairly sure that's a side effect of the underlying DHooks dependency and not specifically this plugin.  Not something I have control of as far as I know, unfortunately.

I'll see if I can grab a post-mortem with GDB at some point, but it's not something I have a particularly high priority for.
It's probably better to raise the issue over at alliedmodders/sourcemod since the extension is under their ownership.

**Comment by ghost** [comment]
Okay, I will close this then since it related to DHooks .
